# -*- mode: ruby -*-
# vi: set ft=ruby :

# Create VitualBox centos/7, assign IP address, assign hostname, assign 2GB memory, 2 cpus
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "172.16.10.101"
  config.vm.hostname = "worker1.xtl"

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = "worker1.xtl"
    vb.cpus = 2
    vb.memory = "2048"

    override.vm.box_download_checksum_type = "sha256"
    override.vm.box_download_checksum = "b24c912b136d2aa9b7b94fc2689b2001c8d04280cf25983123e45b6a52693fb3"
    override.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1803_01.VirtualBox.box"
  end

  # Run file install-docker-kube.sh after loading Box
  config.vm.provision "shell", path: "./../install-docker-kube.sh"

  # Run command shell
  config.vm.provision "shell", inline: <<-SHELL
    # Set password 123 with root account and allow SSH
    echo "123" | passwd --stdin root
    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    systemctl reload sshd
# Write the following content to the file /etc/hosts to access the machines according to HOSTNAME
cat >>/etc/hosts<<EOF
172.16.10.100 master.xtl
172.16.10.101 worker1.xtl
172.16.10.102 worker2.xtl
EOF

  SHELL
end
