# -*- mode: ruby -*-
# vi: set ft=ruby :

# Create VitualBox centos/7, assign IP address, assign hostname, assign 2GB memory, 2 cpus
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "172.16.10.100"
  config.vm.hostname = "master.xtl"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "master.xtl"
     vb.cpus = 2
     vb.memory = "2048"
  end

  # Run file install-docker-kube.sh after loading Box
  config.vm.provision "shell", path: "./../install-docker-kube.sh"

  # Run command shell
  config.vm.provision "shell", inline: <<-SHELL
    # Set password 123 with root account and allow SSH
    echo "123" | passwd --stdin root
    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    systemctl reload sshd
# Write the following content to the file /etc/hosts to access the machines according to HOSTNAME
cat >>/etc/hosts<<EOF
172.16.10.100 master.xtl
172.16.10.101 worker1.xtl
172.16.10.102 worker2.xtl
EOF

  SHELL
end
